### ISSUE TITLE
invalid integer with new fishshell version 

### ISSUE THREAD

**Issue by amir20** [fisherman/dartfish#7] opened 2017-01-05 00:03 UTC
With the new version of fish `version 2.4.0-291-g7211802f` I see the following error

```
test returned eval errors:
	invalid integer ''
```

With `fish -d 3` I see

```
<3> fish: Job is constructed
<3> fish: proc::read_try('set -l status_color 0fc')

<3> fish: Skipping fork: no output for internal builtin 'test'
<3> fish: Set status of test "$status_copy" -ne 0 to 1 using short circuit
<3> fish: Job is constructed
<3> fish: proc::read_try('test "$status_copy" -ne 0')

test returned eval errors:
	invalid integer ''
```

Guessing the culprit is `test "$status_copy" -ne 0` 

Any ideas what is causing this?

**Comment by amir20** [comment] 2017-01-05 22:32
@lordlycastle @jbucaran ping...

**Comment by jbucaran** [comment] 2017-01-06 02:39
@amir20 I am using fish 2.4.0 too and I can't repro the issue.

One more thing, the fix you suggest on the PR does not address `test "$status_copy" -ne 0`, which according to the error log is the culprit.

Could this be a problem with fish, with that version instead?

@faho Can you take a look at the debug [log](https://github.com/fisherman/dartfish/issues/7#issue-198842888)?

**Comment by amir20** [comment] 2017-01-06 15:24
It turns out the problem wasn't with `test "$status_copy" -ne 0`. Just the other one. I haven't installed the latest fish on my work laptop yet. I can do that to see if it happens. I actually installed `HEAD` first and then saw a lot of errors. When I did reinstall latest stable, the error never went away. Perhaps I had a bad install?

**Comment by faho** [comment] 2017-01-06 15:37
>@faho Can you take a look at the debug log?

Sure.

>I am using fish 2.4.0 too and I can't repro the issue.

There's been some changes to how test treats invalid integers since 2.4.0, so that would explain why you're not seeing it. What I don't really get here is how `$status_copy` should be anything _but_ a valid integer.

I also can't seem to reproduce the issue.

@amir20: When does this happen? After every command, or just after failing ones?

Also, what OS is this on and what is your locale?

This could be a duplicate of https://github.com/fish-shell/fish-shell/issues/3050. In particular you'd notice that `echo $status` outputs something, while `echo "$status"` doesn't. The solution would be to upgrade your operating system, as the root cause is a bug there.

**Comment by amir20** [comment] 2017-01-06 15:43
> @amir20: When does this happen? After every command, or just after failing ones?

This only happened when I created a new session or when I resized the window. Resizing the window made it sound like it was the right prompt. So that's how I started debugging. 

> Also, what OS is this on and what is your locale?

I am on Mac OS with EN_US. 

When I do `fisher dartfish` with `fish, version 2.4.0-291-g7211802f` (which was the latest as of a two days ago) I see the above error when I create a new tab everytime. 

How can I provide more debugging info?

**Comment by amir20** [comment] 2017-01-06 15:55
I tried with `fish, version 2.4.0-306-gaf022728` and same error. I am going to try a different laptop next and see if I can reproduce.

**Comment by faho** [comment] 2017-01-06 16:04
Sooo.... $CMD_DURATION is only defined after the first interactive command has been run, which should explain this (an undefined quoted variable expands to the empty string, which isn't an integer - we should probably define $CMD_DURATION always, initially either as 0 or as the startup time). What it doesn't explain is why I don't get an error.

In fact I can't seem to get the (expected) test error _at all_.

So yes, currently this _should_ check `set -q CMD_DURATION` or `test -n "$CMD_DURATION"` (I dislike the POSIX-default of "no option means -n").

**Comment by amir20** [comment] 2017-01-06 18:10
So what do we do? Looks like my PR is almost there.

**Comment by jbucaran** [comment] 2017-01-06 18:51
@amir20 The PR is good and fixes the problem. I left some comments there, please have a look.

Check something for me, open a new tab and type:

```fish
test "$CMD_DURATION" -gt 100
```

**Comment by krader1961** [comment] 2017-01-07 05:22
FYI, I merged commit 573916e5 to ensure `$CMD_DURATION` is defined before the first prompt is written which should fix this issue in the 2.5.0 release that should enter testing soon. Which means your PR #8 shouldn't be needed except for people using fish built from git head in the seven weeks prior to today.

**Comment by jbucaran** [comment] 2017-01-07 06:10
That's wonderful @krader1961.

@amir20 You have the option to downgrade to 2.4.0 sharp, or keep using fish from HEAD. If you go with HEAD, then you have a few options:

1. In your config.fish add `set -g CMD_DURATION 0`
2. Patch dartfish locally.
3. Proceed with #8.

Pick your best. If you proceed with the PR, please address [this comment](https://github.com/fisherman/dartfish/pull/8#discussion_r94998283) and feel free to merge yourself.

**Comment by amir20** [comment] 2017-01-07 16:53
I am leaning to option 3. I'll address that comment and merge today.

**Comment by amir20** [comment] 2017-01-07 22:45
@jbucaran changes made. I'll give it a few hours for comments and merge. 👍

**Comment by amir20** [comment] 2017-01-08 02:56
And it works! Thanks all for playing.

**Closed** 2017-01-08 02:55 UTC

**Comment by terrycojones** [comment] 2017-08-14 10:41
Should this be fixed in 2.6.0?

I just upgraded fish (to 2.6.0) on OS X 10.10.5 using brew upgrade fish. On launching shells iTerm2 I get output as described by the OP. Much worse though, although the shell prints a initial prompt, I can't run any commands. I.e., I can type a first command, but on hitting ENTER the line is erased, cursor goes to column 1, and a gray "b/" is displayed, indented one TAB / 8 spaces. At that point if I type anything, the first 8 chars are not shown, then the subsequent ones are, then when I hit ENTER again the line is erased. I.e., I have a completely non-functional shell.   Fortunately I can launch a shell inside emacs and from there change my login shell.

Thanks for any help!

**Comment by terrycojones** [comment] 2017-08-14 13:09
I switched shells back to bash (better than no shell at all), then ran `brew unlink fish` and installed the HEAD version `brew install --HEAD fish`. Then, from `bash` I run `/usr/local/bin/fish` and get the following:

```sh
$ /usr/local/bin/fish
~/.config/fish/config.fish (line 106): The file '.' is not executable by this user
. $HOME/.config/fish/virtual.fish
^
from sourcing file ~/.config/fish/config.fish
	called during startup

test returned eval errors:
	invalid integer ''
```

The terminal window is completely unusable at that point. Typing echos a space for each keystroke and hitting ENTER just takes the cursor back to the start of the line.

I just checked to see if I get the same behavior when using `Terminal` as I do with `iTerm2`, and I do.

**Comment by faho** [comment] 2017-08-14 13:20
@terrycojones: The issue there is something completely different.

We at fish-shell upstream have removed the `.` function for the upcoming 3.0 major release.

It appears there's been a mixup and it landed on the master branch as well, instead of the "major" branch.

As for your "terminal is unusable" issue, I'd look into keybindings. Also, do you have your configuration uploaded somewhere?

Please open an issue at https://github.com/fish-shell/fish-shell/issues, since I don't think this has anything to do with dartfish.

**Comment by kfir-rocketrip** [comment] 2017-11-29 21:48
<img width="329" alt="screen shot 2017-11-29 at 4 46 16 pm" src="https://user-images.githubusercontent.com/28552777/33400696-ecc0cb30-d524-11e7-88b5-cb2b5ee8f846.png">

Just upgrade fish to `2.7.0-481-g7d055a12` and started getting this error.

**Comment by mgperry** [comment] 2017-12-16 00:13
I've fixed this for my own installation of mono. The variable $CMD_DURATION has been renamed $cmd_duration as per https://github.com/fish-shell/fish-shell/issues/4414. It's possible other variables your prompt uses are affected as well, I think lowercase-ing everything is a safe bet.
